# Generated by Django 5.1.2 on 2024-10-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pwd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
