# Generated by Django 5.1.2 on 2024-10-30 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_question_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='ended',
        ),
        migrations.RemoveField(
            model_name='test',
            name='started',
        ),
    ]
