# Generated by Django 5.1.2 on 2024-10-30 20:06

import tests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_remove_test_ended_remove_test_started'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spec',
            new_name='Set',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='spec',
            new_name='set',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='spec',
            new_name='set',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='employee',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='test',
            name='score',
        ),
        migrations.AddField(
            model_name='test',
            name='cases',
            field=models.JSONField(default=tests.models.json),
        ),
        migrations.AddField(
            model_name='test',
            name='duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='test',
            name='elapsed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(blank=True, choices=[('not_started', 'Boshlanmagan'), ('passed', "O'tgan"), ('failed', 'Yiqilgan'), ('ended', 'Tugagan')], default='not_started', max_length=20, null=True),
        ),
    ]
